export const customerData = [
    { name: 'Jan', activeCustomers: 4000 },
    { name: 'Feb', activeCustomers: 3000 },
    { name: 'Mar', activeCustomers: 2000 },
    { name: 'Apr', activeCustomers: 2780 },
    { name: 'May', activeCustomers: 1890 },
    { name: 'Jun', activeCustomers: 2390 },
    { name: 'Jul', activeCustomers: 3490 },
    { name: 'Aug', activeCustomers: 2000 },
    { name: 'Sep', activeCustomers: 8000 },
    { name: 'Oct', activeCustomers: 1000 },
    { name: 'Nov', activeCustomers: 1780 }, 
    { name: 'Dec', activeCustomers: 190 },
  ];
  
  export const customerRows = [
    {   
        id: 1, userName: 'Kamal Alwis',
        avatar: 'https://www.w3schools.com/howto/img_avatar.png',
        email: 'kamal@gmail.com',
        phoneNumber: "071 123 4567",
        membership:'Active',
        address: 'Muththettugala, Kururnegala',
     },

     {   
      id: 2, userName: 'Kamal Alwis',
      avatar: 'https://www.w3schools.com/howto/img_avatar.png',
      email: 'kamal@gmail.com',
      phoneNumber: "071 123 4567",
      membership:'Active',
      address: 'Muththettugala, Kururnegala',
   },

   {   
    id: 3, userName: 'Kamal Alwis',
    avatar: 'https://www.w3schools.com/howto/img_avatar.png',
    email: 'kamal@gmail.com',
    phoneNumber: "071 123 4567",
    membership:'Active',
    address: 'Muththettugala, Kururnegala',
 },

 {   
  id: 4, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},

{   
  id: 5, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},

{   
  id: 6, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},
{   
  id: 7, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},
{   
  id: 8, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},
  
   
  ];

  export const productRows = [
    {   
        id: 1, productName: 'Chocolate Biscuits',
        avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
        company: 'Munchee',
        category: "Snacks",
        price: '100',
        stock:"320",
        description: 'Chocolate Biscuits taste better when u eating these kind of our products',
     },
     {   
      id: 1, productName: 'Chocolate Biscuits',
      avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
      company: 'Munchee',
      category: "Snacks",
      price: '100',
      stock:"320",
      description: 'Chocolate Biscuits taste better when u eating these kind of our products',
   },
   {   
    id: 1, productName: 'Chocolate Biscuits',
    avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
    company: 'Munchee',
    category: "Snacks",
    price: '100',
    stock:"320",
    description: 'Chocolate Biscuits taste better when u eating these kind of our products',
 },
 {   
  id: 1, productName: 'Chocolate Biscuits',
  avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
  company: 'Munchee',
  category: "Snacks",
  price: '100',
  stock:"320",
  description: 'Chocolate Biscuits taste better when u eating these kind of our products',
},
{   
  id: 1, productName: 'Chocolate Biscuits',
  avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
  company: 'Munchee',
  category: "Snacks",
  price: '100',
  stock:"320",
  description: 'Chocolate Biscuits taste better when u eating these kind of our products',
},
  ];

  export const data = [
    { name: 'Grocery', stock: 120 },
    { name: 'Dairy & Eggs', stock: 80 },
    { name: 'Meats & Seafoods', stock: 50 },
    { name: 'Frozen Foods', stock: 65 },
    { name: 'Beverages', stock: 95 },
    { name: 'Snacks', stock: 75 },
    { name: 'Bakery Foods', stock: 60 },
    { name: 'Health & Wellness', stock: 40 },
  ];

  export const productData = {
    Biscuits: [
      { month: 'January', sales: 40 },
      { month: 'February', sales: 35 },
      { month: 'March', sales: 50 },
      { month: 'April', sales: 55 },
      { month: 'May', sales: 40 },
      { month: 'June', sales: 35 },
      { month: 'July', sales: 50 },
      { month: 'August', sales: 55 },
      { month: 'September', sales: 40 },
      { month: 'October', sales: 35 },
      { month: 'November', sales: 50 },
      { month: 'December', sales: 55 },
    ],
    Flour: [
      { month: 'January', sales: 60 },
      { month: 'February', sales: 70 },
      { month: 'March', sales: 65 },
      { month: 'April', sales: 80 },
      { month: 'May', sales: 40 },
      { month: 'June', sales: 35 },
      { month: 'July', sales: 50 },
      { month: 'August', sales: 55 },
      { month: 'September', sales: 40 },
      { month: 'October', sales: 35 },
      { month: 'November', sales: 50 },
      { month: 'December', sales: 55 },
    ],
    Noodles: [
      { month: 'January', sales: 25 },
      { month: 'February', sales: 30 },
      { month: 'March', sales: 40 },
      { month: 'April', sales: 50 },
      { month: 'May', sales: 40 },
      { month: 'June', sales: 35 },
      { month: 'July', sales: 50 },
      { month: 'August', sales: 55 },
      { month: 'September', sales: 40 },
      { month: 'October', sales: 35 },
      { month: 'November', sales: 50 },
      { month: 'December', sales: 55 },
    ],
    Pasta: [
      { month: 'January', sales: 45 },
      { month: 'February', sales: 50 },
      { month: 'March', sales: 60 },
      { month: 'April', sales: 70 },
      { month: 'May', sales: 40 },
      { month: 'June', sales: 35 },
      { month: 'July', sales: 50 },
      { month: 'August', sales: 55 },
      { month: 'September', sales: 40 },
      { month: 'October', sales: 35 },
      { month: 'November', sales: 50 },
      { month: 'December', sales: 55 },
    ],
    Rice: [
      { month: 'January', sales: 70 },
      { month: 'February', sales: 80 },
      { month: 'March', sales: 75 },
      { month: 'April', sales: 85 },
      { month: 'May', sales: 60 },
      { month: 'June', sales: 65 },
      { month: 'July', sales: 75 },
      { month: 'August', sales: 85 },
      { month: 'September', sales: 60 },
      { month: 'October', sales: 65 },
      { month: 'November', sales: 75 },
      { month: 'December', sales: 85 },
    ],
    Sugar: [
      { month: 'January', sales: 55 },
      { month: 'February', sales: 60 },
      { month: 'March', sales: 65 },
      { month: 'April', sales: 70 },
      { month: 'May', sales: 50 },
      { month: 'June', sales: 55 },
      { month: 'July', sales: 65 },
      { month: 'August', sales: 70 },
      { month: 'September', sales: 50 },
      { month: 'October', sales: 55 },
      { month: 'November', sales: 65 },
      { month: 'December', sales: 70 },
    ],
    Oil: [
      { month: 'January', sales: 90 },
      { month: 'February', sales: 100 },
      { month: 'March', sales: 95 },
      { month: 'April', sales: 105 },
      { month: 'May', sales: 85 },
      { month: 'June', sales: 90 },
      { month: 'July', sales: 95 },
      { month: 'August', sales: 105 },
      { month: 'September', sales: 85 },
      { month: 'October', sales: 90 },
      { month: 'November', sales: 95 },
      { month: 'December', sales: 105 },
    ],
   
    Bread: [
      { month: 'January', sales: 45 },
      { month: 'February', sales: 50 },
      { month: 'March', sales: 55 },
      { month: 'April', sales: 60 },
      { month: 'May', sales: 40 },
      { month: 'June', sales: 45 },
      { month: 'July', sales: 55 },
      { month: 'August', sales: 60 },
      { month: 'September', sales: 40 },
      { month: 'October', sales: 45 },
      { month: 'November', sales: 55 },
      { month: 'December', sales: 60 },
    ],
    CannedFoods: [
      { month: 'January', sales: 50 },
      { month: 'February', sales: 55 },
      { month: 'March', sales: 60 },
      { month: 'April', sales: 65 },
      { month: 'May', sales: 45 },
      { month: 'June', sales: 50 },
      { month: 'July', sales: 60 },
      { month: 'August', sales: 65 },
      { month: 'September', sales: 45 },
      { month: 'October', sales: 50 },
      { month: 'November', sales: 60 },
      { month: 'December', sales: 65 },
    ],
    
  };

  export const productCompanies = {
    Biscuits: ['Munchee', 'Maliban'],
    Flour: ['Prima', 'Sarathchandra'],
    Noodles: ['Prima', 'Maggie'],
    Pasta: ['Luzia', 'Carolina'],
    Rice: ['Araliya', 'Nipuna', 'Rathna'],
    Sugar: ['Lucky Products', 'Orients'],
    Oil: ['Turkey Brand', 'Marina', 'Fortune'],
    Bread: ['Prima'],
    CannedFoods: ['Tuna Fish', 'Jam'],
    // Milk: ['Anchor', 'Highland','Palawaththa'],
  };