export const customerData = [
    { name: 'Jan', activeCustomers: 4000 },
    { name: 'Feb', activeCustomers: 3000 },
    { name: 'Mar', activeCustomers: 2000 },
    { name: 'Apr', activeCustomers: 2780 },
    { name: 'May', activeCustomers: 1890 },
    { name: 'Jun', activeCustomers: 2390 },
    { name: 'Jul', activeCustomers: 3490 },
    { name: 'Aug', activeCustomers: 2000 },
    { name: 'Sep', activeCustomers: 8000 },
    { name: 'Oct', activeCustomers: 1000 },
    { name: 'Nov', activeCustomers: 1780 }, 
    { name: 'Dec', activeCustomers: 190 },
  ];
  
  export const customerRows = [
    {   
        id: 1, userName: 'Kamal Alwis',
        avatar: 'https://www.w3schools.com/howto/img_avatar.png',
        email: 'kamal@gmail.com',
        phoneNumber: "071 123 4567",
        membership:'Active',
        address: 'Muththettugala, Kururnegala',
     },

     {   
      id: 2, userName: 'Kamal Alwis',
      avatar: 'https://www.w3schools.com/howto/img_avatar.png',
      email: 'kamal@gmail.com',
      phoneNumber: "071 123 4567",
      membership:'Active',
      address: 'Muththettugala, Kururnegala',
   },

   {   
    id: 3, userName: 'Kamal Alwis',
    avatar: 'https://www.w3schools.com/howto/img_avatar.png',
    email: 'kamal@gmail.com',
    phoneNumber: "071 123 4567",
    membership:'Active',
    address: 'Muththettugala, Kururnegala',
 },

 {   
  id: 4, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},

{   
  id: 5, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},

{   
  id: 6, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},
{   
  id: 7, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},
{   
  id: 8, userName: 'Kamal Alwis',
  avatar: 'https://www.w3schools.com/howto/img_avatar.png',
  email: 'kamal@gmail.com',
  phoneNumber: "071 123 4567",
  membership:'Active',
  address: 'Muththettugala, Kururnegala',
},
  
   
  ];

  export const productRows = [
    {   
        id: 1, productName: 'Chocolate Biscuits',
        avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
        company: 'Munchee',
        category: "Snacks",
        price: '100',
        stock:"320",
        description: 'Chocolate Biscuits taste better when u eating these kind of our products',
     },
     {   
      id: 1, productName: 'Chocolate Biscuits',
      avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
      company: 'Munchee',
      category: "Snacks",
      price: '100',
      stock:"320",
      description: 'Chocolate Biscuits taste better when u eating these kind of our products',
   },
   {   
    id: 1, productName: 'Chocolate Biscuits',
    avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
    company: 'Munchee',
    category: "Snacks",
    price: '100',
    stock:"320",
    description: 'Chocolate Biscuits taste better when u eating these kind of our products',
 },
 {   
  id: 1, productName: 'Chocolate Biscuits',
  avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
  company: 'Munchee',
  category: "Snacks",
  price: '100',
  stock:"320",
  description: 'Chocolate Biscuits taste better when u eating these kind of our products',
},
{   
  id: 1, productName: 'Chocolate Biscuits',
  avatar: 'https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/114800--01--1623926473.webp',
  company: 'Munchee',
  category: "Snacks",
  price: '100',
  stock:"320",
  description: 'Chocolate Biscuits taste better when u eating these kind of our products',
},
  ];

  export const data = [
    { name: 'Grocery', stock: 120 },
    { name: 'Dairy & Eggs', stock: 80 },
    { name: 'Meats & Seafoods', stock: 50 },
    { name: 'Frozen Foods', stock: 65 },
    { name: 'Beverages', stock: 95 },
    { name: 'Snacks', stock: 75 },
    { name: 'Bakery Foods', stock: 60 },
    { name: 'Health & Wellness', stock: 40 },
  ];


  export const productData = {
    Flour: [
      { month: 'January', stocks: 60 },
      { month: 'February', stocks: 70 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 80 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Noodles: [
      { month: 'January', stocks: 25 },
      { month: 'February', stocks: 30 },
      { month: 'March', stocks: 40 },
      { month: 'April', stocks: 50 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Pasta: [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Rice: [
      { month: 'January', stocks: 70 },
      { month: 'February', stocks: 80 },
      { month: 'March', stocks: 75 },
      { month: 'April', stocks: 85 },
      { month: 'May', stocks: 60 },
      { month: 'June', stocks: 65 },
      { month: 'July', stocks: 75 },
      { month: 'August', stocks: 85 },
      { month: 'September', stocks: 60 },
      { month: 'October', stocks: 65 },
      { month: 'November', stocks: 75 },
      { month: 'December', stocks: 85 },
    ],
    Sugar: [
      { month: 'January', stocks: 55 },
      { month: 'February', stocks: 60 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 50 },
      { month: 'June', stocks: 55 },
      { month: 'July', stocks: 65 },
      { month: 'August', stocks: 70 },
      { month: 'September', stocks: 50 },
      { month: 'October', stocks: 55 },
      { month: 'November', stocks: 65 },
      { month: 'December', stocks: 70 },
    ],
    Oil: [
      { month: 'January', stocks: 90 },
      { month: 'February', stocks: 100 },
      { month: 'March', stocks: 95 },
      { month: 'April', stocks: 105 },
      { month: 'May', stocks: 85 },
      { month: 'June', stocks: 90 },
      { month: 'July', stocks: 95 },
      { month: 'August', stocks: 105 },
      { month: 'September', stocks: 85 },
      { month: 'October', stocks: 90 },
      { month: 'November', stocks: 95 },
      { month: 'December', stocks: 105 },
    ],
    Bread: [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 55 },
      { month: 'April', stocks: 60 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 45 },
      { month: 'July', stocks: 55 },
      { month: 'August', stocks: 60 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 45 },
      { month: 'November', stocks: 55 },
      { month: 'December', stocks: 60 },
    ],
    Jam: [
      { month: 'January', stocks: 50 },
      { month: 'February', stocks: 55 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 65 },
      { month: 'May', stocks: 45 },
      { month: 'June', stocks: 50 },
      { month: 'July', stocks: 60 },
      { month: 'August', stocks: 65 },
      { month: 'September', stocks: 45 },
      { month: 'October', stocks: 50 },
      { month: 'November', stocks: 60 },
      { month: 'December', stocks: 65 },
    ],
  };
  
  export const productCompanies = {
    Flour: ['Prima', 'Sarathchandra'],
    Noodles: ['Prima', 'Maggie'],
    Pasta: ['Luzia', 'Carolina'],
    Rice: ['Araliya', 'Nipuna', 'Rathna'],
    Sugar: ['Lucky Products', 'Orients'],
    Oil: ['Turkey Brand', 'Marina', 'Fortune'],
    Bread: ['Prima'],
    Jam: ['MD products', 'Kist'],
  };


  export const productData2 = {
    Milk: [
      { month: 'January', stocks: 60 },
      { month: 'February', stocks: 70 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 80 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Cheese: [
      { month: 'January', stocks: 25 },
      { month: 'February', stocks: 30 },
      { month: 'March', stocks: 40 },
      { month: 'April', stocks: 50 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Yoghurt: [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Butter: [
      { month: 'January', stocks: 70 },
      { month: 'February', stocks: 80 },
      { month: 'March', stocks: 75 },
      { month: 'April', stocks: 85 },
      { month: 'May', stocks: 60 },
      { month: 'June', stocks: 65 },
      { month: 'July', stocks: 75 },
      { month: 'August', stocks: 85 },
      { month: 'September', stocks: 60 },
      { month: 'October', stocks: 65 },
      { month: 'November', stocks: 75 },
      { month: 'December', stocks: 85 },
    ],
    Eggs: [
      { month: 'January', stocks: 55 },
      { month: 'February', stocks: 60 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 50 },
      { month: 'June', stocks: 55 },
      { month: 'July', stocks: 65 },
      { month: 'August', stocks: 70 },
      { month: 'September', stocks: 50 },
      { month: 'October', stocks: 55 },
      { month: 'November', stocks: 65 },
      { month: 'December', stocks: 70 },
    ],
    
  };
  
  export const productCompanies2 = {
    Milk: ['Anchor', 'Highland','Palawaththa'],
    Cheese: ['Anchor', 'Kraft','Kotmale'],
    Yogurt: ['Anchor', 'Yoplait', 'Ambewela','Kotmale'],
    Butter: ['Anchor', 'Kotmale', 'Raththi'],
    Eggs: ['Happy Hen','Crysbro'],
  };
  

  export const productData3 = {
    Chicken: [
      { month: 'January', stocks: 60 },
      { month: 'February', stocks: 70 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 80 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Beef: [
      { month: 'January', stocks: 25 },
      { month: 'February', stocks: 30 },
      { month: 'March', stocks: 40 },
      { month: 'April', stocks: 50 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Pork: [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Fish: [
      { month: 'January', stocks: 70 },
      { month: 'February', stocks: 80 },
      { month: 'March', stocks: 75 },
      { month: 'April', stocks: 85 },
      { month: 'May', stocks: 60 },
      { month: 'June', stocks: 65 },
      { month: 'July', stocks: 75 },
      { month: 'August', stocks: 85 },
      { month: 'September', stocks: 60 },
      { month: 'October', stocks: 65 },
      { month: 'November', stocks: 75 },
      { month: 'December', stocks: 85 },
    ],
    
    
  };
  
  export const productCompanies3 = {
    Chicken: ['Crysbro', 'Bairaha'],
    Beef: ['MeatCo', 'Local'],
    Fish: ['Canned Tuna', 'Tora Fish', 'Teppiliya Fish'],
    Pork:['Local Pork'],
  };

  

  export const productData4 = {
    'Ice Cream': [
      { month: 'January', stocks: 60 },
      { month: 'February', stocks: 70 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 80 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Sausages: [
      { month: 'January', stocks: 25 },
      { month: 'February', stocks: 30 },
      { month: 'March', stocks: 40 },
      { month: 'April', stocks: 50 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Ham: [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    
  };
  
  export const productCompanies4 = {
    'Ice Cream': ['Elephant House', 'Cargills'],
    Sausages: ['Elephant House', 'Cargills', 'Prima'],
    Ham: ['Elephant House', 'Cargills', 'Prima'],
  };

  
  export const productData5 = {
    'Juice': [
      { month: 'January', stocks: 60 },
      { month: 'February', stocks: 70 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 80 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    'Soft Drinks': [
      { month: 'January', stocks: 25 },
      { month: 'February', stocks: 30 },
      { month: 'March', stocks: 40 },
      { month: 'April', stocks: 50 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Water: [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    
  };
  
  export const productCompanies5 = {
    Juice: ['Richlife', 'Cargills', 'Elephant House'],
    'Soft Drinks': ['Coca Cola', 'Pepsi', 'Sprite', 'Fanta','EGB'],
    Water: ['Nestle', 'Supan Water'],
  };

  export const productData6 = {
    Chips: [
      { month: 'January', stocks: 60 },
      { month: 'February', stocks: 70 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 80 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Candy: [
      { month: 'January', stocks: 25 },
      { month: 'February', stocks: 30 },
      { month: 'March', stocks: 40 },
      { month: 'April', stocks: 50 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Biscuits: [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    
  };
  
  export const productCompanies6 = {
    Chips: ['Lays', 'Pringles', 'Cheetos'],
    Candy: ['M&Ms', 'Snickers', 'KitKat','Mars','Bounty','Twix'],
    Biscuits: ['Munchee', 'Maliban', 'Uswatta Products'],
  };

  export const productData7 = {
    Cakes: [
      { month: 'January', stocks: 60 },
      { month: 'February', stocks: 70 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 80 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Cookies: [
      { month: 'January', stocks: 25 },
      { month: 'February', stocks: 30 },
      { month: 'March', stocks: 40 },
      { month: 'April', stocks: 50 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    'Short-Eats': [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    
  };
  
  export const productCompanies7 = {
    Cakes: ['Tiara', 'Wijaya Cakes'],
    Cookies: ['Choco Mo', "Chipie Chap"],
    'Short-Eats':['Dissanayake Bakers'],
  };

  export const productData8 = {
    Vitamins: [
      { month: 'January', stocks: 60 },
      { month: 'February', stocks: 70 },
      { month: 'March', stocks: 65 },
      { month: 'April', stocks: 80 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    Suppliments: [
      { month: 'January', stocks: 25 },
      { month: 'February', stocks: 30 },
      { month: 'March', stocks: 40 },
      { month: 'April', stocks: 50 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    'Herbal-Products': [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    'Medicines': [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    'Cleaning-Products': [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    'Soap & Shampoo': [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    'Face-Wash Products': [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    'Personal Care': [
      { month: 'January', stocks: 45 },
      { month: 'February', stocks: 50 },
      { month: 'March', stocks: 60 },
      { month: 'April', stocks: 70 },
      { month: 'May', stocks: 40 },
      { month: 'June', stocks: 35 },
      { month: 'July', stocks: 50 },
      { month: 'August', stocks: 55 },
      { month: 'September', stocks: 40 },
      { month: 'October', stocks: 35 },
      { month: 'November', stocks: 50 },
      { month: 'December', stocks: 55 },
    ],
    
  };
  
  export const productCompanies8 = {
    Vitamins: ['Local Vitamins'],
    Supplements:['Mars Products', 'Carnivorous','Lighting Energy'],
    'Herbal Products':['Nature Secrets','Spa Ceylon'],
    Medicines:['Panadol','Paracitamol','Sidhdhalepa','IoDEX Bam'],
    'Cleaning Products':['Harpic','Bio-Clean'],
    'Soap & Shampoo':['Dave', 'Pears', 'Baby Sheramie'],
    'Face Wash Products':['Nature Secrets','Fair & Lovely', 'Fair & Handsome' ],
    'Personal Care': ['Signal','Clogard','Fems','Arya']
  };
  
  